# Site settings
title: Errant Schwa
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and musings of Max Anderson, a self-professed terrible
  programmer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://errantschwa.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  MFAnderson

# Build settings
markdown: kramdown
